name: My CI
on:
  push:
    branches: 
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-versions: [3.5, 3.6]
    steps:
      - uses: actions/checkout@v2
      - name: Run my tryout Python script.
        run: |
          echo ${{ matrix.python-versions }}
          python3 tryout.py

